### ISSUE TITLE
Cross Protocol JS error when loading posts over https

### ISSUE THREAD

**Issue by rjulianialtimetrik** [godofredoninja/simply#1]
First of all, thanks a lot for this theme. It's awesome and I loved it!

I'm trying to use it for my blog and while everything seems to work fine, there's a problem when loading posts via AJAX for the infinite scroll. Basically, my blog is being served as HTTPS, and it would seem the js tries to load the next batch of posts for any given list via HTTP, which causes an issue in the browser.

I've tried debugging this myself, but since the code is minified, I seem to be unable to locate the part of the code that's always using http. Can you please help me fix this? 

Thanks a lot!

**Comment by godofredoninja** [comment]
Hello.

How are you.

— I am using the following link canonical For infinite pagination.

![2017-02-24 08_52_54-godofredo](https://cloud.githubusercontent.com/assets/10253167/23306066/9595c436-fa6f-11e6-9729-481fc4e67533.png)

— The most suitable solution is to have it configured in your ghost configuration by adding in production your url https.

![2017-02-24 09_01_16- config js - visual studio code](https://cloud.githubusercontent.com/assets/10253167/23306142/145e0fd0-fa70-11e6-9ff2-b67a60f883ce.png)

**Comment by rjulianialtimetrik** [comment]
@godofredoninja Thanks a lot for your suggestion. It worked like a charm! 

Thanks again for your work on ghost themes!
