### ISSUE TITLE
How to add drop caps and pull qoutes to a text?

### ISSUE THREAD

**Issue by kuhlenbrecht** [godofredoninja/simply#101]
Hi,

I saw on the screenshot of "Post Default" [1] that you added drop caps, pull quotes and infoboxes to a post. However, I didn't find how to do that in the documentation. How do you do it?

[1] https://godofredo.ninja/ghost-theme/simply/post-format/#postdefault

**Comment by godofredoninja** [comment]
Read Here  #103
