### ISSUE TITLE
Icons are broken

### ISSUE THREAD

**Issue by pascalandy** [godofredoninja/simply#11]
Hi,
I just retried the theme and Icons are still broken. Is there something I have to do about this?

![glitch-simple-ghost-theme](https://user-images.githubusercontent.com/6694151/31904966-abcaa944-b7fa-11e7-9873-81457df4f3b1.jpeg)

Cheers!

**Comment by godofredoninja** [comment]
Hi.
Plase .

You can share the domain to be able to help you better

**Comment by pascalandy** [comment]
As I did set up a fresh environment to show you, the icons are loading correctly now. I guess there was some issue with the cache. Thank you again !!

**Comment by godofredoninja** [comment]
— it gives me a lot of happiness that works well

—  if you have suggestions to improve the theme, you can tell me so that you can add them in the following versions

**Comment by pascalandy** [comment]
Sure!

**Comment by pascalandy** [comment]
Well well. The problem is back. 
See: https://play-with-ghost.com/demo-barbershop-simply/

I can switch to other templates and it's all fine. 
Check out https://play-with-ghost.com/demo-barbershop-klimax2/contact-us/ 
which is based on Casper

I guess there is something fragile in the way the theme manage the icons.

Thanks in advance!

**Comment by godofredoninja** [comment]
There is an error in calling the font.

because you are making a call from the root of the folder.

to be able to solve add the piece of code in the header part in the code section in your ghost configuration

```html
<style>
@font-face{
    font-family:simply;
    src:url(https://play-with-ghost.com/demo-barbershop-simply/assets/fonts/simply.eot);
    src:url(https://play-with-ghost.com/demo-barbershop-simply/assets/fonts/simply.eot#iefix) format("embedded-opentype"),
        url(https://play-with-ghost.com/demo-barbershop-simply/assets/fonts/simply.ttf) format("truetype"),
        url(https://play-with-ghost.com/demo-barbershop-simply/assets/fonts/simply.woff) format("woff"),
        url(https://play-with-ghost.com/demo-barbershop-simply/assets/fonts/simply.svg#simply) format("svg");
</style>
```
