### ISSUE TITLE
Is there any way to remove the "Subscribe" button?

### ISSUE THREAD

**Issue by Hasslek** [godofredoninja/simply#112]
I am not currently using the membership system, so I would like to remove it from the menu.

This includes the "Subscribe" button and the "Log in" button.

![imagen](https://user-images.githubusercontent.com/31199840/150677658-bb428d97-2168-4236-98a5-b11203d2cb51.png)

I would also like to know how to add the table of contents automatically to the posts.

Thanks for the amazing theme @godofredoninja !

**Comment by kiraitachi** [comment]
Yes

```
<style type='text/css'>
    a.button.is-primary { display: none; }
</style>
```

On the code Injection header section.
