### ISSUE TITLE
Search in other languages

### ISSUE THREAD

**Issue by uPagge** [godofredoninja/simply#118]
Prior to updating the theme, the search worked in all languages. But now it only works in English

**Comment by godofredoninja** [comment]
Hi.

Thank you 

You are very right

In the SearchinGhost documentation it says so.. but at the moment my theme only works by default.

I will add support for the next update.

The reason I have switched to another search engine is to use local storage.

https://github.com/gmfmi/searchinGhost#language-settings

**Comment by uPagge** [comment]
Thank you very much

**Comment by uPagge** [comment]
unfortunately, none of the settings helped me to return the search(

**Comment by godofredoninja** [comment]
Hi.

My question is, what language or languages do you want to add to the search engine?

**For example for: Chinese, Korean, Japanese**

```html
<script>
    var searchSettings = {
        key: "ADD_YOUR_CONTENT_API_KEY",
        indexOptions: {
            encode: false,
            tokenize: function(str){
                return str.replace(/[\x00-\x7F]/g, "").split("");
            }
        }
    };
</script>
```

or Mixed language

https://github.com/gmfmi/searchinGhost#mixed-language-types

**Comment by uPagge** [comment]
<img width="770" alt="Снимок экрана 2022-05-16 в 18 24 23" src="https://user-images.githubusercontent.com/40397740/168627935-5778572c-24e8-46f7-8da3-0cc58384ad4a.png">

I am trying to use the search in Russian and English, that is, it is a multilingual search in

**Comment by uPagge** [comment]
Strange, but nothing works for me :(

<img width="1242" alt="Снимок экрана 2022-05-16 в 20 09 36" src="https://user-images.githubusercontent.com/40397740/168646713-3c78f4f3-ee9b-4d30-be33-26956df0a487.png">

**Comment by godofredoninja** [comment]
🤔 

It may be because of the cache. Try in a private tab or delete the data from local storage.

![image](https://user-images.githubusercontent.com/10253167/168647533-d3b90d55-10c8-42df-ba9c-ddb8cf7c9fe7.png)

**Comment by uPagge** [comment]
Indeed, everything works in incognito mode, but clearing the cache did not help, strange

**Comment by uPagge** [comment]
> I will steal some blog ideas to add to Simply. 🏴‍☠️

I am intrigued. If it's not a secret what chips I liked, I can still throw ideas :)

**Comment by godofredoninja** [comment]
> Indeed, everything works in incognito mode, but clearing the cache did not help, strange

Here is a better explanation.
https://github.com/gmfmi/searchinGhost#why-does-my-new-article-not-appear-in-the-search-results

**Comment by godofredoninja** [comment]
> I am intrigued. If it's not a secret, what chips did you like? I can add more ideas :)

What caught my attention is the scroll bar that is in the header as you read the article, also the table of contents.

**Comment by uPagge** [comment]
Well, the scrollbar is quite easy to add, I think you'll figure it out yourself :) I stole this feature myself from another site :D

And about the content. I did it with your kusidoc template. In order for any post template to be able to use the content, I made the table of contents display if the author specifies the "#toc" tag

It's pretty clumsy, but it works :)

<img width="1254" alt="Снимок экрана 2022-05-16 в 20 59 50" src="https://user-images.githubusercontent.com/40397740/168654538-8007294b-e882-4342-b33c-9d1814e2c021.png">
