### ISSUE TITLE
Feedback recommandation

### ISSUE THREAD

**Issue by pascalandy** [godofredoninja/simply#12]
Hi,

### One
When I click on the author's pages I think it should behave like the /blog (the root of the site.)

<img width="675" alt="screen shot 2017-10-29 at 9 35 36 pm" src="https://user-images.githubusercontent.com/6694151/32151204-52be2028-bcf1-11e7-8b80-e7a9cf216635.png">

Instead, I would put elements in this order

- Title
- Image
- Preview
- The `read more ...` at the end of the paragraph
- Author

Also, the link for `read more ...` is grey and not following the rest of the website.

### Links

All links are in black. Many ppl don't realize they are URL :-p
I would put them in green just like the header of the website

Cheers!

**Comment by godofredoninja** [comment]
This section is inspired by medium. for example you can see the equality in the following page of author of medium

https://arcdigital.media/@nicholasgrossman
