### ISSUE TITLE
upgrade to v5 error

### ISSUE THREAD

**Issue by topikuning** [godofredoninja/simply#120]
when I'm trying to upgrade ghost version to v5, there is fatal error caused by themes, the error said
Errors
    File: members/membership.hbs
    - Fatal error: Replace {{@price.currency}} with {{#get "tiers"}} and {{currency}} or {{#foreach @member.subscriptions}} and {{plan.currency}}
    - Fatal error: Replace {{@price.monthly}} and {{@price.yearly}} with {{#get "tiers"}} and {{monthly_price}} or {{yearly_price}}

I hope there is a solution for this in main release.

thank you

**Comment by ssinghm32** [comment]
BUMP. @godofredoninja 

I'm looking to upgrade my Ghost to 5.0 and I'm running into similar issues.

You can use the following website to check for 5.0 compatibility issues.
https://gscan.ghost.org/

**Comment by godofredoninja** [comment]
I will update tomorrow. Sorry people. 😅 GodoFredoFreelance . Developer . Frontend . Backend.Diseño y Desarrollo de aplicaciones WebGodoFredo.ninja ---- On lun, 13 jun 2022 12:19:04 -0500  ***@***.***  wrote ----
I get the same error with version 5.0

**Comment by Charly1000** [comment]
same here. Can't use anymore this great template

**Comment by slavache** [comment]
theme dont updated to ghost 5x, please update!

**Comment by helczyna** [comment]
Please update!
