### ISSUE TITLE
Turn off image zoom

### ISSUE THREAD

**Issue by glenn-irs** [godofredoninja/simply#13]
Hello!
Thank you so much for this fantastic Ghost theme!

I have a page where I'm using small social icons: LinkedIn, Instagram, etc, as links to social sites. I just want them to be buttons, not to zoom in on the icons as if they were photographs which seems to be the theme default.

Is there a way to turn this off?
Page at:
http://beacharts.ca/490/fall17/

Thank you!!

**Comment by godofredoninja** [comment]
Hello
 How are you? 😀

— I am very happy thank you for your donation through PayPal ❤

> if you like the new version of simply. can you update your ghost

---

— replace the code of your images for this

```html
<p class="not-zoom">
    <a href="http://juliepavlacka.com" target="_blank">
        <img src="http://xuefaith.co.uk/links/www.png" alt="www" title="WWW" style="width:79px;height:64px;padding-right:15px;" align="left" />
    </a>      
    <a href="http://linkedin.com/in/juliepavlacka" target="_blank">
        <img src="http://xuefaith.co.uk/links/linkedin.png" alt="linkedin" title="LINKEDIN" style="width:79px;height:64px;padding-right:15px;" align="left"/>
    </a>      
    <a href="http://instagram.com/juliepavlacka" target="_blank">
        <img src="http://xuefaith.co.uk/links/instagram.png" alt="instagram" title="INSTAGRAM" style="width:79px;height:64px;padding-right:15px;" align="left"/>
    </a>      
    <a href="http://flickr.com/photos/pavlacka" target="_blank">
        <img src="http://xuefaith.co.uk/links/flickr.png" alt="flickr" title="FLICKR" style="width:64px;height:64px;" align="left" />
    </a> 
</p>
```

— add this piece of code in your ghost settings in the code section and footer

```html
<script>
setTimeout(function(){
  $('.not-zoom').find('img').removeAttr('data-action');
}, 500);
</script>>
```
### If you need more help, please tell me I will help you

**Comment by godofredoninja** [comment]
please check these boxes in your ghost settings

https://github.com/godofredoninja/simply/tree/0.0.2#simply-settings

**Comment by glenn-irs** [comment]
Hi, you're welcome! :)
Thanks for such a nice theme. And for all the details in it!

ONE
Thank you! That bit of code worked great! Problem solved! :)

TWO
I checked the Ghost API boxes. Thanks for reminding me! Nice to have search engine & related articles.

THREE
Well... I'm working on updating Ghost. :P 
The current Ghost 0.11 site was installed with Softaculous. With the release of Ghost 1.0, Ghost switched to CLI install only, and Softaculous dropped Ghost, so I'm struggling to do a Ghost 1.0 install. I'm trying to follow these steps:
https://docs.ghost.org/v1/docs/install

I'm currently stuck on:
usermod -aG sudo <user>

I asked tech support at Liquid Web (my web host) for help, but they're a little slow, so it's taking a while to sort it out.

Anyway, I'll upgrade to 1.0 eventually, but it's taking a while.


Thanks again for the beautiful work and for your help with the buttons!!
