### ISSUE TITLE
Integrate with built-in search feature

### ISSUE THREAD

**Issue by yogeshbeniwal** [godofredoninja/simply#132]
Ghost has released built-in search feature. Theme using this feature won't require any additional custom integration by users.

**Comment by uPagge** [comment]
Yes, I'm also looking forward to updating this theme with new functionality.

**Comment by bobtstacc** [comment]
Hi, while you at it, can we have a "table of contents" it's a handy feature, plus a "back to top button" would be very helpful...for cosmetic reason having a "Reading Position Indicator bar" at the top of the page maybe looks good...thank you.

**Comment by bobtstacc** [comment]
Hi, while you at it, can we have a "back to top button" it would be very handy plus adding a "Reading Position Indicator bar" at the top of the page maybe looks good too? thank you.
