### ISSUE TITLE
Add native comments support

### ISSUE THREAD

**Issue by yogeshbeniwal** [godofredoninja/simply#137]
v5.9.1 release has added support for native comments. Enabling comments in admin area is still not showing comment section on frontend.

**Comment by timscha** [comment]
I would love to see support for that too!

**Comment by uPagge** [comment]
What are native comments?

**Comment by timscha** [comment]
@uPagge Ghost introduced comments as a feature in the latest release.

**Comment by uPagge** [comment]
Curious, but I have not seen a description of this functionality anywhere.

**Comment by yogeshbeniwal** [comment]
@uPagge It's on release page on [Github](https://github.com/TryGhost/Ghost/releases/tag/v5.9.1)

**Comment by uPagge** [comment]
Yes, they already posted an announcement.  but as long as there is no oauth2 there, I see no reason to switch to it
