### ISSUE TITLE
Forwarding to welcome page of tiers not working 

### ISSUE THREAD

**Issue by timscha** [godofredoninja/simply#139]
Hi!
I am not sure if that is a ghost related issue or a problem with the theme.
I created several tiers and also added welcome pages for them. Unfortunately the theme/ghost does not forward the user after he subscribed to one plan. He will be forwarded to the homepage instead.

Is there some routing thing I have to update?

**Comment by timscha** [comment]
I did some more researching. I have two more Ghost blogs installed identically but with another theme. There I don't have the problem.

**Comment by godofredoninja** [comment]
Hello.

Do you still have that problem or did you already get a solution.

Because things about redirection I would have no problem. Also Simply uses portal.

**Comment by timscha** [comment]
Hello,
yes unfortunately the problem still exists.

**Comment by timscha** [comment]
Forget what I just wrote. I have no idea why, but now it is working. :)
