### ISSUE TITLE
Public preview element is not working

### ISSUE THREAD

**Issue by HamedMP** [godofredoninja/simply#148]
Hi, 

Thanks for the cool template. 

I'm trying to separate the content between subscribed users and public visitors, but the element is not working correctly and the content below it which should be only for subscribed users is still shown for any visitor. 

<img width="898" alt="image" src="https://user-images.githubusercontent.com/3755031/206909298-4b41b5f2-a20d-434c-9312-f4a639661199.png">

Becomes (opening it in Incognito and not logged in):
<img width="845" alt="image" src="https://user-images.githubusercontent.com/3755031/206909313-6971d0f2-dc14-4de4-becb-a4378d6b1c60.png">

Expected: The text below the element should only be shown if you are a member.

**Comment by godofredoninja** [comment]
Hi.

In your article you have marked. In the dropdown you have marked for members.

![image](https://user-images.githubusercontent.com/10253167/207115871-94622a82-093b-4ec3-9855-69ada8ce6999.png)

**Comment by HamedMP** [comment]
Oh, that's right! Thank you, didn't know that one is required too. It's working now.

I'd suggest adding it to the documentation on your website ❤️
