### ISSUE TITLE
Share / Comment counter not working!

### ISSUE THREAD

**Issue by FinleyCorrigan** [godofredoninja/simply#16]
Hey,

Sorry to bother you again, but the share/comment counter doesn't work!

Here's a screenshot of what I mean: https://gyazo.com/367b6038a93cacee12549ab2af2dd5c7

As you can see, I have commented, but the comment counter does not update! You can see for yourself at https://techy-news.com/about. 

Please help me!

Thanks

**Comment by godofredoninja** [comment]
I will check it to see if there is any problem

**Comment by FinleyCorrigan** [comment]
fixed!
