### ISSUE TITLE
Some social icons are not showing

### ISSUE THREAD

**Issue by jusuchin85** [godofredoninja/simply#17]
I have a few of social network sites that I've added into the `THEME SETTINGS & GLOBAL VARIABLES` script. This script is then pasted into the **Code Injection** section of Ghost.

All the social icons are rendering, except for two: the Google+ and RSS icon.

My site can be seen here: https://justinalex.com . The Google+ icon is positioned between the Instagram and Twitter icons. The RSS icon is placed after the Linkedin icon.

Am I missing something, or a bug?

The following are the code blocks I used for Google+ and RSS:
```
var followSocialMedia = {
  'google': 'https://plus.google.com/+JustinalexCodingForMe',
  'youtube': 'https://...',
  'instagram': 'https://www.instagram.com/jusuchin85',
  'snapchat': 'https://...',
  'dribbble': 'https://...',
  'github': 'https://...',
  'linkedin':'https://www.linkedin.com/in/pjustinalex',
  'spotify':'https://...',
  'codepen':'https://...',
  'behance':'https://...',
  'flickr':'https://...',
  'pinterest':'https://...',
  'telegram':'https://...',
  'feed':'http://feeds.feedburner.com/CodingForMe',
};
```

**Comment by godofredoninja** [comment]
Hi

how are you?

**Excuse me.**
the fault is me and not you, for the next version I will add the google + icon

```js
var followSocialMedia = {
  'instagram': 'https://www.instagram.com/jusuchin85',
  'linkedin':'https://www.linkedin.com/in/pjustinalex',
  'rss':'http://feeds.feedburner.com/CodingForMe',
};
```

**Comment by jusuchin85** [comment]
Hi @godofredoninja ,

I'm good! Hope you are well too! :)

I've fixed the **RSS** icon. Thanks for that.

Now all that is left is the **Google** icon. :)

**Comment by godofredoninja** [comment]
the new version already has the google icon
