### ISSUE TITLE
Discourse integration with Ghost

### ISSUE THREAD

**Issue by yogeshbeniwal** [godofredoninja/simply#19]
[Discourse ](https://www.discourse.org/) provides comment feature for ghost. Official guide for using Discourse as commenting system is at https://help.ghost.org/article/35-discourse.

However I have tried all possible methods, but blog post doesn't show comments. It is stuck at **Loading Discussion...** as shown below
![discourse ghost integration](https://user-images.githubusercontent.com/7325107/36211361-03db52a6-11dc-11e8-93b7-8c5b35e3e91a.png)

I have tried below possible methods

- Follow official integration guide to put code directly in post.hbs/article.hbs
- use partials to integrate discourse code in article.hbs
- Put only div section in article.hbs, while script section in Code Injection --> Blog footer

Can you look into this issue

**Comment by godofredoninja** [comment]
Hi @yogeshbeniwal 

— replace the following code with this
 `<div id='discourse-comments'></div>`

https://github.com/godofredoninja/simply/blob/6809dfc20bd5ef97ba96ad74292734036f5d8e05/partials/article-comments.hbs#L3-L6

—  replace add the following code with the corresponding configurations
```javascript
DiscourseEmbed = { discourseUrl: 'http://discourse.example.com/',
                     discourseEmbedUrl: 'http://example.com/blog/entry-123.html' };

  (function() {
    var d = document.createElement('script'); d.type = 'text/javascript'; d.async = true;
    d.src = DiscourseEmbed.discourseUrl + 'javascripts/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(d);
  })();
```

https://github.com/godofredoninja/simply/blob/6809dfc20bd5ef97ba96ad74292734036f5d8e05/partials/article-comments.hbs#L15-L32

**Comment by yogeshbeniwal** [comment]
Thanks that helped

**Comment by yogeshbeniwal** [comment]
Is there any way to reflect number of comments in footer for each post?
