### ISSUE TITLE
AMP template changes as to make similar to non-amp page

### ISSUE THREAD

**Issue by yogeshbeniwal** [godofredoninja/simply#20]
Hi,

Will it be possible to make below changes in order to make AMP page look similar to non-amp pages

**1. Same header color**

Simply changing color on line 23 <style amp-custom>.u-bgColor{background-color: ##C1CBDB } change the color but look different

_AMP page header color_
![amp page header color](https://user-images.githubusercontent.com/7325107/36243410-5ac207ec-125c-11e8-8219-a6fba38eba2c.png)

_Non-AMP page header color_
![non-amp page header color](https://user-images.githubusercontent.com/7325107/36243411-5dfd2c2a-125c-11e8-907c-e14a48ab12ca.png)

**2. Same font size and formatting**

Non-AMP page text is bigger in size and more clear than AMP page

_AMP page text_
![amp page text](https://user-images.githubusercontent.com/7325107/36243527-cf926756-125c-11e8-8793-8c868fa689c5.png)

_Non-AMP page text_
![non-amp page text](https://user-images.githubusercontent.com/7325107/36243536-ddc323ce-125c-11e8-9630-c1df74a78fae.png)

**3. Option to add icon in footer for: Linkedin, Google+ and RSS feed etc**

Option to add all Social media link in AMP footer as supported by below code in Settings -> Code Injection -> Blog Footer section

/* 01. Social Media Follow*/
var followSocialMedia = {

**Comment by godofredoninja** [comment]
Hi 😀

Can you share your page to help you better?

**Comment by yogeshbeniwal** [comment]
Sure, here are links
https://www.ankitaism.com/blog/
https://www.ankitaism.com/blog/introduction-to-recurrent-neural-networks-rnn/
https://www.ankitaism.com/blog/introduction-to-recurrent-neural-networks-rnn/amp/

**Comment by godofredoninja** [comment]
Hi @yogeshbeniwal 

— code to change the color of the header

`.u-bgColor{background-color:#1E3757}`

— the text in the pages amp is smaller because it is only for mobiles and has a better reading of content

— Amp does not allow scripts or variables

First solution is to add the icons in an SVG and directly in the file `amp.hbs`
