### ISSUE TITLE
Logo on AMP page

### ISSUE THREAD

**Issue by yogeshbeniwal** [godofredoninja/simply#21]
Its a suggestion to replace blog-title on AMP page with header-logo as done in Non-AMP pages

**Comment by godofredoninja** [comment]
Hi @yogeshbeniwal 

— uncomment these lines.

but in the width and height properties ` width="110" height="30"`  you have to add exact sizes of your reduced logo so you do not have problems with amp

https://github.com/godofredoninja/simply/blob/6809dfc20bd5ef97ba96ad74292734036f5d8e05/amp.hbs#L74-L78

— after uncomment these lines
https://github.com/godofredoninja/simply/blob/6809dfc20bd5ef97ba96ad74292734036f5d8e05/amp.hbs#L81

**Comment by yogeshbeniwal** [comment]
I think instead of uncommenting it's, comment below line

`<a href="{{@blog.url}}" class="logo-link u-flex1">{{@blog.title}}</a> `

Also doing this is making menu to move extreme left, any CSS settings to keep it extreme right?
