### ISSUE TITLE
Is it allowed to use the theme for the blog of a company?

### ISSUE THREAD

**Issue by abhinavsohani** [godofredoninja/simply#29]
Hi @godofredoninja,
This is one of the best themes available for Ghost. Great stuff.
Is it allowed to use this theme for the blog of a company? 
It is mentioned in the readme that commercial use is strictly prohibited. What qualifies as the commercial usage in case of theme?

**Comment by godofredoninja** [comment]
Hello. 😄 

You can use the theme for free for the company you want. I sincerely hope that the company makes a donation to continue working 💻  and updating the theme.
