### ISSUE TITLE
how did you did this!

### ISSUE THREAD

**Issue by systemroot** [godofredoninja/simply#3]
i'm trying to put a image at header but also i want to use a color at my menu, 
and 
![](http://image.prntscr.com/image/59c1594706c44a22abb8920f5f4a4bec.png)

the menu should be something like green but isn't getting the color, maybe can i have some help?!

exactly like this
![](http://image.prntscr.com/image/29df2ab749e14177a75cc692e0fce320.png)

Thank you!

**Comment by godofredoninja** [comment]
Hi @systemroot  how are you?

Those little adjustments just corrected for me.
Because I do not receive apollo and that's why I no longer update

But you can send your url to help you

**Comment by systemroot** [comment]
bad to hear that! Your work is pretty good! 

as for me i found a solution as for now, Blog http://systemroot.me/

**Comment by godofredoninja** [comment]
@systemroot 

Add this piece of code to your ghost admin panel.

`Code injection> blog header`

```html
<style>
.header>nav { 
    background: #00a034;
}
</style>
```

**Comment by systemroot** [comment]
thank you
