### ISSUE TITLE
Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by mnlttt** [godofredoninja/simply#32]
**Steps to reproduce**
Scroll the page when you're into a blog post.

`cmd+F` on `o>r.top` into `assets/scripts/main.js` to find the referenced `top`.
Since `main.js` is minified is hard to debug.

**Comment by godofredoninja** [comment]
Hi @mnlttt 

I'm using Simply theme for ghost and I don't have problems

You can make a screenshot with the error or share your page.

**Comment by mnlttt** [comment]
Fresh install of Ghost (inside docker)

<img width="1680" alt="schermata 2019-02-26 alle 08 58 34" src="https://user-images.githubusercontent.com/37709016/53396467-c8ee7000-39a4-11e9-8023-1ae7a7e2d1b7.png">
