### ISSUE TITLE
How can I change the frontend of this theme ?

### ISSUE THREAD

**Issue by patidarparas13** [godofredoninja/simply#33]
I want to make theme more customizable, according to my requirement. 
Can I use Bootstrap as a framework to do that ?

**Comment by godofredoninja** [comment]
hi @patidarparas13 

If you want you can enhance modifications according to your wishes.

But I am not using Bootstrap.

But you can add the library and play a little.

**Comment by Rahulsharma0810** [comment]
@godofredoninja what css framework you are using ?

**Comment by godofredoninja** [comment]
Hi @MertcanGokgoz  

I'm not using framework. I'm using my own css. but next week I'll release the code so you can modify it to your liking.

**Comment by godofredoninja** [comment]
If you want to make changes. use the dev branch

https://github.com/godofredoninja/simply/tree/dev
