### ISSUE TITLE
social media icons not visible in the new header and footer

### ISSUE THREAD

**Issue by ivanrodjr** [godofredoninja/simply#38]
*Summary*

Social media icons and search icon are not visible in header or footer of the new update, as soon as I activate previous version they work.

Icons tested: Github, twitter, linkedIn

*Steps to reproduce*
- Add icon links in code footer as in the documentation

*Actual Results*
- Icons are not visible in the header or footer.
- Twitter icon is the only one present, but not visible, you can click on it.

*Expected Results*
- Icons are present and visible

*Workaround*
- None

- Version 0.2.7
- Chrome 77, Mac Catalina
- Ghost 3

**Comment by godofredoninja** [comment]
## Hello

I had the same problem. But restart ghost. it's a cache problem

If you manage to see my blog. I just updated and everything works fine.

But I will check it anyway to see if I find any problem.

https://godofredo.ninja/

**Comment by warmbo** [comment]
Just want to say this bug has returned and now the only social media icon present ever is Facebook, no others work.
