### ISSUE TITLE
Facebook sharing doesn't seem to work. 

### ISSUE THREAD

**Issue by mrkitchenmagpie** [godofredoninja/simply#40]
When attempting to share this page: https://www.cmscritic.com/email-newsletters-natively-with-ghost/ using the built in icons from this theme; it does not work as shown in the attached screenshot.

![Screenshot from 2019-12-10 07-19-34](https://user-images.githubusercontent.com/50334585/70537357-89e96f80-1b1d-11ea-8c88-2be21ddd31c2.png)

**Comment by godofredoninja** [comment]
### Hello :smile: 

It's working well. :thinking: 

![facebook-share](https://user-images.githubusercontent.com/10253167/70549113-adbeac80-1b41-11ea-84ea-01dfd31a4d8b.png)

**Comment by thatcriticguy** [comment]
Oops must have been a caching issue. My bad! Btw I sent you an email about my donation monthly for mapache. I didn't hear back. Was wondering if you could make a small addition to simply for me.

**Comment by godofredoninja** [comment]
Thank you, my friend :heart_eyes: 

I just sent you an email. :smile:

**Comment by godofredoninja** [comment]
### I already made your request

I've created a branch especially for you.

https://github.com/godofredoninja/simply/tree/mike

:smile: It looks good. I think the next versions will add it to the main theme.

![Selección_004](https://user-images.githubusercontent.com/10253167/70562603-b4a5e900-1b5a-11ea-99c5-a3118e93656b.jpg)

**Comment by mrkitchenmagpie** [comment]
Looks awesome thanks!

-------- Original Message --------
