### ISSUE TITLE
Question: Homepage with Featured Post

### ISSUE THREAD

**Issue by MrNovy** [godofredoninja/simply#41]
Hi!

I use your style "simply" and for the homepage I use the layout option "With Featured Post". The problem now is that the first post with the large image (featured post) is displayed practically twice. 

For example, if i activate my latest written post as featured post, the post will even be displayed twice in a row! How can I set / program that a featured post is only shown in the first post and no longer on the homepage below?

**Comment by godofredoninja** [comment]
Hello :smile: 

:arrow_right:  To do that, it's very easy. Just edit this line of code.

https://github.com/godofredoninja/simply/blob/0d75e4ba1c15c8d390b82cd4aef0e4ba4441b919/godo-template-featured.hbs#L8

Now add this line of code. but you have to add your tag. for example `Hello im Video Tag` or an internal tag for example `#video`

:arrow_right:  To do that, it's very easy. Just edit this line of code.

For a normal tag, everything has to be in minuscule.

```hbs
{{#get "posts" filter="tags:hello-im-video-tag" limit="1" as |godo_featured_post| }}
```

For internal Tag
```hbs
{{#get "posts" filter="tags:hash-video" limit="1" as |godo_featured_post| }}
```

**Comment by MrNovy** [comment]
Thanks a lot! It worked!

One problem remains! The posts are practically displayed twice!
For example, if I use the code for internal tags, the post will appear as the first post with a large image and at another location on the homepage again. 

I want that the first post only one time will be displayed at the homepage (as first post). Only after i replace the first post with a new one the post should be displayed at another place at the homepage...
