### ISSUE TITLE
Search functionality is not working for me.

### ISSUE THREAD

**Issue by AnkitMaheshwariIn** [godofredoninja/simply#45]
This is the URL of my website:
https://www.codewithchintan.com/

When I search something - that does not result anything.
I added Integration and SearchSettings as per defined in the Simply link: 
https://github.com/godofredoninja/simply#5-search

Please help in fix search.
Thanks!

**Comment by godofredoninja** [comment]
## Hello :smile: 
The problem is this `/` in the URL

```html
<script>
 var searchSettings = {
    key: 'e6c4edbd45d4f93b1ff3326b50',
    url: 'https://ankitmaheshwari.ghost.io',
  };
</script>
```

**Comment by AnkitMaheshwariIn** [comment]
Thanks! By mistake I added / at the end of URL. Fixed it to https://ankitmaheshwari.ghost.io
It worked.
Thanks! Again :-)
