### ISSUE TITLE
The translation of "Subscribe to ..." does not work for the YouTube video

### ISSUE THREAD

**Issue by antomal** [godofredoninja/simply#47]
Hello!
The translation of "Subscribe to ..." does not work for the YouTube video (see screenshot).
I use RU localization. There is a line in file [simply/locales/ru.json](https://github.com/godofredoninja/simply/blob/master/locales/ru.json). But on the site "Subscribe to ..."

![Снимок экрана 2020-01-31 в 6 11 42](https://user-images.githubusercontent.com/44556749/73509563-96d56180-43f0-11ea-9891-42ae020a93b9.png)

**Comment by godofredoninja** [comment]
😢  I understand. Now Simply no longer has that functionality
