### ISSUE TITLE
Incompatible Restrictions on GPLv3 Code

### ISSUE THREAD

**Issue by dippersauce** [godofredoninja/simply#5]
According to the FSF and the GNU Foundation the GPLv3 license cannot have non-commercial restrictions placed on the work under the GPLv3 license. You could create a derivative license, but there may be problems enforcing it.

https://www.gnu.org/licenses/gpl-faq.en.html#NoMilitary

**Comment by irfanrulz** [comment]
No Support for ads, In Header Leaderboard Add can easily be accomdated and also in content you can have rectangle ads too

**Comment by dippersauce** [comment]
Not sure how this is relevant @irfanrulz. Could you elaborate?

**Comment by irfanrulz** [comment]
Sorry had to put it up separately.... Actually it's a feature request... If you could have  place holders for ads it would be great.. So far this is the best theme I have come across in ghost

**Comment by dippersauce** [comment]
I could look into implementing that.

**Comment by dippersauce** [comment]
Is the feature request specifically for fallback placeholders in the event the ads don’t load, or permanent placeholders?

**Comment by irfanrulz** [comment]
placeholders need to be permanent , even if they don't load design needs to accommodate their presence . 

i have some more suggestions shall i post them  in separate threads

**Comment by godofredoninja** [comment]
@dippersauce  
— I simply want people to use this theme for free. But I would not like to be marketed

**Comment by godofredoninja** [comment]
@irfanrulz 
— If you want to add ad to your blog. You can do it by adding code in the part that you think is more relevant

— If you have any suggestions you can share or make screenshots. To be able to include in the following versions

**Comment by irfanrulz** [comment]
@godofredoninja  i appreciate your concerns , and its your call as you are the owner. couple of  suggestions i have are as follows
1. Simply has a potential for magazine theme.  since we dont have categories here we can club them in tags and show as follows:
  >Feature post needs to be a seperate section at Top.
  > Tags can be treated as Categories . maximum posts in a tag be at top rest following 
2.  header can have different formats like following : 
   >Logo on left Nav on Right
   > Logo at centre Nav Below  etc
You can check my implementation of your theme here http://www.kashmirnarrative.com

**Comment by dippersauce** [comment]
@godofredoninja
May I suggest you re-licence the theme under a Creative Commons Non-Commercial license? It will allow people to use your theme, modify it, but not use it commercially. It fits your stated goals and will be enforceable should issues arise in the future.
