### ISSUE TITLE
Not loading certain elements of theme

### ISSUE THREAD

**Issue by Vibhigupta** [godofredoninja/simply#52]
Hello I loved your theme so I switch from Liebling theme to your's.

Although there are some issues I faced
1. Feature image aren't loading on main page and related post section. They are blurred for some reason
2.The share button icon are not loading as well
3. Navigation menu isn't working means I'm clicking it but it's not opening the menu

I switched back to older theme for now, if you want to look I can immediately switch to yours

![Screenshot_2020-04-13-11-06-17-59_3aea4af51f236e4932235fdada7d1643__01](https://user-images.githubusercontent.com/51713176/79102636-a3642780-7d5a-11ea-9db1-a291281f0bcd.png)
![Screenshot_2020-04-13-11-09-32-15_3aea4af51f236e4932235fdada7d1643__01](https://user-images.githubusercontent.com/51713176/79102642-a828db80-7d5a-11ea-9f7b-9738ac1dec66.png)
![Screenshot_2020-04-13-11-10-00-54_3aea4af51f236e4932235fdada7d1643__01](https://user-images.githubusercontent.com/51713176/79102649-ac54f900-7d5a-11ea-9bdf-9f78a51c51f6.png)
![Screenshot_2020-04-13-12-23-17-97_cbf47468f7ecfbd8ebcc46bf9cc626da__01](https://user-images.githubusercontent.com/51713176/79102662-b0811680-7d5a-11ea-9a32-873625fbdbca.png)

**Comment by Vibhigupta** [comment]
And no dark mode option

**Comment by godofredoninja** [comment]
Hello @Vibhigupta 

Clears the browser cache. If it doesn't work then restarts the server to clear the cache and generate a new cache

**Comment by Vibhigupta** [comment]
I cleared the browser cache and even used Private tab.

As I mentioned I did restarted the server.
If you wanna check I can activate theme for you now.

**Comment by Vibhigupta** [comment]
Theme is activated
Server is restarted 
Cleared every type cache
Same issue 

Site thenewsspan.in

**Comment by godofredoninja** [comment]
:thinking: 

if you made changes to the theme. check that the script

https://github.com/godofredoninja/simply/blob/5a5e710c5eefa4a8132bb35e55add78c6628544e/default.hbs#L102

**Comment by Vibhigupta** [comment]
Haven't done any changes to theme, the only thing I did, added ads.text file in it.

And right now I uploaded theme where i haven't added ads.txt

Still same issue.

**Comment by godofredoninja** [comment]
:thinking: 

I think you're using version 0.2.7 of simply

in that version simply had problems. 

Please use version [0.2.8](https://github.com/godofredoninja/simply/releases) of simply

**Comment by Vibhigupta** [comment]
Aye aye Captain

**Comment by Vibhigupta** [comment]
Although @godofredoninja 
In white version or demo image of theme
there is a post on top with big image and text, how to get that?

**Comment by godofredoninja** [comment]
:nerd_face:  Hey 

Doing this is very easy. Please read the documentation

https://github.com/godofredoninja/simply#home-page
