### ISSUE TITLE
Adding ads to post 

### ISSUE THREAD

**Issue by Vibhigupta** [godofredoninja/simply#53]
I wanted to add advertisement to post
1.One Under Feature image basically under Tittle
2.In the middle of post
3.In the end of post

I added Js to head via code Injection. 
Now I have to add a tag to show different ads. 

```
<div id="379524153">
    <script type="text/javascript">
        try {
            window._mNHandle.queue.push(function (){
                window._mNDetails.loadTag("379524153", "300x600", "379524153");
            });
        }
        catch (error) {}
    </script>
</div>
```
It's need to be added in post.hbs but I don't know where to add these tag so ads will appear on particular place

**Comment by Vibhigupta** [comment]
Looking into Post.hbs seems like in have to put the the code under this code

```
      <figure class="post-image u-block u-marginAuto u-sizeFullHeight u-sizeFullWidth u-maxWidth1000">
            <img class="u-block u-marginAuto u-sizeFullWidth simply-zoom"
                srcset="{{img_url feature_image size="s"}} 300w,
                        {{img_url feature_image size="m"}} 600w,
                        {{img_url feature_image size="l"}} 1000w,
                        {{img_url feature_image size="xl"}} 2000w"
                sizes="(max-width: 400px) 300px,(max-width: 730px) 600px, (max-width: 1600px) 100vw"
                src="{{img_url feature_image size="xl"}}"
                alt="{{title}}"
            />
        </figure>
    {{/if}}

```

Then the end of the post under this code

```
<footer class="post-footer u-container u-maxWidth740">
        {{!-- Tags (category) --}}
        {{> "article/article-tags"}}

```

Although I don't know how to put ads in middle of post 

```

<div id="post-body" class="post-body u-container u-maxWidth740 u-relative">{{content}}</div>
    </div>

```

Can you help a bit on this @godofredoninja

**Comment by godofredoninja** [comment]
Hello @Vibhigupta 

You can refer to version [0.2.6](https://github.com/godofredoninja/simply/tree/0.2.6#ads) of simply to add ads.

**creating files to add ads** 

https://github.com/godofredoninja/simply/tree/0.2.6/partials/ad

### Add your ads in these sections

1. Ad article header

`{{> "ad-article-header"}}`

https://github.com/godofredoninja/simply/blob/5a5e710c5eefa4a8132bb35e55add78c6628544e/post.hbs#L12

2. Ad Article Medium
{{> "ad-article-medium"}}

https://github.com/godofredoninja/simply/blob/5a5e710c5eefa4a8132bb35e55add78c6628544e/post.hbs#L35

3. Ad Article Footer

`{{> "ad-article-footer"}}`

https://github.com/godofredoninja/simply/blob/5a5e710c5eefa4a8132bb35e55add78c6628544e/post.hbs#L54


You can add your ads in the most convenient places. Then with a little style you make the necessary adjustments
