### ISSUE TITLE
Different Comments platform such as Commento?

### ISSUE THREAD

**Issue by AKG152** [godofredoninja/simply#56]
Hi,

First off fantastic theme.

Would it be possible to include the ability to use a different commenting system such as Commento?

Disqus integration is great but i have privacy concerns around it.

Cheers!

**Comment by tolgaaaltas** [comment]
Go to partials/article/article-comments.hbs and change the Disqus code.

**Comment by godofredoninja** [comment]
I took the time to add multiple comments. You can see here how to add more comments. 

https://godofredo.ninja/ghost-theme/simply/settings/#comments
