### ISSUE TITLE
Changing fonts

### ISSUE THREAD

**Issue by partizan007** [godofredoninja/simply#59]
Hi,
Thanks for your amazing work!!!

I am noob in Ghost CMS)))
How can I change fonts in your theme?

**Comment by godofredoninja** [comment]
Hi 

Make typeface change you have to remove the old typeface here and add the new typefaces

https://github.com/godofredoninja/simply/blob/8bb53f79c392b9d4979765b78c5f0c0eeb66f00b/default.hbs#L24-L25

Then you need to add the name of the new typography. You can do it in your dashboard of ghost in the section code then header

```html
<style>
/* Global Typography and Titles */
.button, .godo-ne-form, .kg-bookmark-container, body, h1, h2, h3, h4, h5, h6,.kg-bookmark-title, .u-contentTitle {
    font-family: add_here_your_font
}

/* Typography for post content */
.godo-f-story-excerpt, .hhp-excerpt, .ne-e, .post-body, .post-excerpt, .site-archive-des, .spc-c-excerpt, .spc-des, .story-excerpt {
    font-family: add_here_your_font
}
</style>
```

**Comment by partizan007** [comment]
Thank you!!!
