### ISSUE TITLE
Add sidebar to home and posts

### ISSUE THREAD

**Issue by shubhank008** [godofredoninja/simply#6]
First of all, really great theme. Probably one of the best ones I have seen from Ghost, so really appreciate the work.  

I wanted to add the sidebar to the homepage and my posts page (actually all pages), is it possible ? If so, how ?

**Comment by godofredoninja** [comment]
Hi!! @shubhank008  

## Thanks for using simply for ghost 😀

of course.
Tell me, what version of ghost are you using?

**Comment by shubhank008** [comment]
I am using with docker so its 0.11.xx (bitnami image) and using 0.2x version of your theme

**Comment by shubhank008** [comment]
@godofredoninja wondering if any update :D

**Comment by godofredoninja** [comment]
Is inspired, in the design of medium.

**— But, I can make a special one for you**

Send me screenshot making the modifications you need

Send me to this email — hello@godofredo.ninja

**Comment by shubhank008** [comment]
Actually don't need that big of a change or anything custom.
The /tags/ page already uses a sidebar (/partials/sidebar.hbs) so just want to know how to add/include the same sidebar on the homepage and posts page
