### ISSUE TITLE
Table of Content

### ISSUE THREAD

**Issue by adryanev** [godofredoninja/simply#64]
Hi, I want to request a feature to add table of content to posts.
Maybe you can implement with `custom-post-toc.hbs`.

Thanks

**Comment by godofredoninja** [comment]
Hi.

It is already included in the new version. There will also be many different templates. It will be a new improved and multipurpose version of Simply.

For the moment I finished the mockup for Simply. In this week I will write a beautiful code. but it will be in my free time. for the weekend I will probably finish.

**Comment by adryanev** [comment]
Thank you for replying.
I'm very excited to hear about many great feature for upcoming release.

Thank you for your hard work!
