### ISSUE TITLE
Sidebar like mapache theme

### ISSUE THREAD

**Issue by geetansh** [godofredoninja/simply#65]
is there a way to add sidebar on post page of simply theme - just like mapache.
Thanks

**Comment by godofredoninja** [comment]
### Hi @geetansh 

I will try to add `custom-post-sidebar.hbs`. but it will be a very simple sidebar. 

Because it simply is characterized by being very clean

**Comment by geetansh** [comment]
Much appreciated, Thanks alot :)

**Comment by godofredoninja** [comment]
Now Simply comes with a template for posts with sidebar also for the home page

Post format sidebar
https://godofredo.ninja/ghost-theme/simply/post-format/#postsidebar

Home page sidebar
https://godofredo.ninja/ghost-theme/simply/home/#sidebar
