### ISSUE TITLE
Logo on the theme

### ISSUE THREAD

**Issue by Saim-Khan1** [godofredoninja/simply#67]
Hi there! 

I’m quite new to Ghost, and I was thinking of using this theme since it looks so clean and slick! 
I noticed on your website that you’ve got this cool green logo with “GFN” letters - is there any way to replicate that? I’m sorry if this isn’t directly related to the theme, but I just thought it looked really cool haha :) 

Thanks!

**Comment by godofredoninja** [comment]
Hello.

Using my personal logo is not a good idea. If you like I can send you the gradient
