### ISSUE TITLE
Let me know if I can help :-p

### ISSUE THREAD

**Issue by pascalandy** [godofredoninja/simply#7]
Hi,

I just tried your theme over Ghost 1.5.2 and I se a lot of potential! . I’m the owner of [play-with-ghost](http://play-with-ghost.com/) and one big feature I'm working on is to showcase templates like your that I enjoy. 

Let me know if I can help you by hosting a staging environment of your Ghost project(s) or anything related of the backend of hosting Ghost.

Cheers!
[Pascal](https://twitter.com/askpascalandy/)

**Comment by pascalandy** [comment]
I'm about to update your based on your recent work. It looks outstanding! Keep up the good work :)

**Comment by godofredoninja** [comment]
Hello. @pascalandy 

🙏  Sorry I haven't responded to you in a long time.

Thank you for your appreciation. 

Now the Simply theme is more organized, it's not perfect but I try to make it understandable.
