### ISSUE TITLE
Instagram widget receives 400 from Instagram API

### ISSUE THREAD

**Issue by allexeye** [godofredoninja/simply#70]
Hi! Looks like Instagram deprecated the API endpoint 

GET `https://api.instagram.com/v1/users/ID/media/recent/?access_token=xxx&count=10&callback=?`

returns

```
meta: {code: 400, error_type: "APINotAllowedError", error_message: "This endpoint has been retired"}
code: 400
error_message: "This endpoint has been retired"
error_type: "APINotAllowedError"
```

The widget is not visible b/c of this

**Comment by godofredoninja** [comment]
Hi.

 Instagram has made changes to the API.  It is for this reason that it no
longer works.

 At the moment I do not have a computer to continue working, but there will
be news soon.

**Comment by godofredoninja** [comment]
😢 The new version of simply no longer includes the Instagram photo gallery.
