### ISSUE TITLE
No menu below subscribe banner causing issues

### ISSUE THREAD

**Issue by edapm** [godofredoninja/simply#71]
Hi @godofredoninja, I'm using the theme and it's great. However, the Medium homepage doesn't work.
It looks like this:
![image](https://user-images.githubusercontent.com/67737851/97808975-f3a4c780-1c61-11eb-955a-7f97c10c9047.png)
I've added secondary navigation but it doesn't work.

Any clues?

Ed (@edapm)

**Comment by matheus-rossi** [comment]
same as me here ...

**Comment by matheus-rossi** [comment]
Just added some padding to the div and it's all ok

**Comment by edapm** [comment]
> 
> 
> Just added some padding to the div and it's all ok

Okay I'll try that, thanks @matheus-rossi.
Where exactly did you add the padding, could you share the code please?

Thanks, @edapm

**Comment by edapm** [comment]
Yep added 50px padding onto `.homeHero-container`, which works great!

#### Code below ⬇️
https://git.io/JkfRG
