### ISSUE TITLE
Member only or paid member only posts does not listed on homepage by public

### ISSUE THREAD

**Issue by ayyilmaz** [godofredoninja/simply#77]
Private posts are not listed on homepage. I think we shoul see their titles images etc. on homepage.

**Comment by godofredoninja** [comment]
Hello how are you.

Simply does not support the latest version of ghost at the moment.

Simply is still in development.

You can download version 3 of simply and see its new features. 

[simply-v0.3.0.zip](https://github.com/godofredoninja/simply/files/5751214/simply-v0.3.0.zip)
