### ISSUE TITLE
Feature Request - Dark & Light version of logo

### ISSUE THREAD

**Issue by jotcodeofficial** [godofredoninja/simply#79]
Being able to change to dark and light on the theme is really cool.

However if you have a light or dark logo then in dark or light mode it will not look normal (dark on dark)

It would be great if we could upload two logos (dark and light) so that when the theme is set to dark mode it would show the light logo.

**Comment by raspberrycoulis** [comment]
+1 for this

**Comment by godofredoninja** [comment]
Hi @jotcodeofficial @raspberrycoulis 

1. Add your logo for dark mode in the folder `assets/images/logo-dark-mode.png`

2. Now you have to uncomment this line

https://github.com/godofredoninja/simply/blob/cc21e3c9f70a939bf4169f7001c05ce8271898ad/partials/layout/header.hbs#L13

3. Add the entyles in ➡️ `Dashboard -> Code injection -> Site Header`

```html
<style>
   .is-head-transparent .logo-default,
    .dark .logo-default { display: none !important }
    
  	.is-head-transparent:not(.has-menu) .logo-dark-mode, 
    .dark .logo-dark-mode { display: block }
</style>
```
