### ISSUE TITLE
how to change the format and colors of tags 

### ISSUE THREAD

**Issue by Mateuspier** [godofredoninja/simply#82]
Hello,

Dear Simply community, I'm officially a newbie.

I brought a couple questions:

1- I would like to change the tags as the picture below (both in the headers of the posts and in the footer of the page).

![tete](https://user-images.githubusercontent.com/78273147/108405891-b7a66a00-7232-11eb-8192-63b35b48dc90.png)

2- Also, I would like to insert the medium Icon, since I have a blog out there.
Exactly as these icons:

![tete1](https://user-images.githubusercontent.com/78273147/108406080-efadad00-7232-11eb-8cc8-cc2cc21f7893.png)

3- And how can I insert a menu like that on my footer?

![menutete](https://user-images.githubusercontent.com/78273147/108406325-559a3480-7233-11eb-85d6-d94591d53cbd.png)

Please, teach me how can I do it.

Greetings from the other side of the world,
Pier

**Comment by godofredoninja** [comment]
Hey @Mateuspier 

How are you?

I'm using Simply version 3.

https://github.com/godofredoninja/simply/tree/dev

I am not publishing it in the main branch, because I still need to finish the documentation.

1. Footer Menu and Tags
https://godofredo.ninja/ghost-theme/simply/layouts/#footerdark

2. Icons
https://godofredo.ninja/ghost-theme/simply/settings/#socialmedia

To set colors in the tags you have to do it from your ghost administrator in the tags section.

**Comment by Mateuspier** [comment]
Hi @godofredoninja 

Thanks a lot.

1- Could I use the simply version 3?
2- I didn't see the Medium icon, even when I modified the id name for icon-medium. Should I download a new icon image? I would like to use the same family of icon.
3- Where do you recommend hosting my simply? Heroku, Netlify or Digital Ocean? 
4- I would like to insert a picture at the sidebar of my homepage with my actual template? (https://soudefora.com)

**Comment by Mateuspier** [comment]
Hello @godofredoninja

**Comment by godofredoninja** [comment]
Hi @Mateuspier 

1.  It is now available and you can use
2. The medium icon can be found here. https://ionicons.com/
3.   [Digitalocean](https://m.do.co/c/710a27a3b3de) is an alternative to start with small projects. Netlify for jamstack
4.  Then you would have to use the template with sidebar. [Home Sidebar](https://godofredo.ninja/ghost-theme/simply/home/#sidebar)
5. Remove this code
 
https://github.com/godofredoninja/simply/blob/cc21e3c9f70a939bf4169f7001c05ce8271898ad/partials/navigation.hbs#L56-L69

6. You have to remove the script. and add the page

https://github.com/godofredoninja/simply/blob/cc21e3c9f70a939bf4169f7001c05ce8271898ad/default.hbs#L92

Below this line add your page you have to do the same with the page of tags and authors

https://github.com/godofredoninja/simply/blob/cc21e3c9f70a939bf4169f7001c05ce8271898ad/index.hbs#L24

7. I think this page is different from simply. If you want a page similar to the reference, you would have to create a custom one.
8. Cut this code

https://github.com/godofredoninja/simply/blob/cc21e3c9f70a939bf4169f7001c05ce8271898ad/partials/story/story-grid.hbs#L16-L22

The cut code paste here

https://github.com/godofredoninja/simply/blob/cc21e3c9f70a939bf4169f7001c05ce8271898ad/partials/story/story-grid.hbs#L35

9. Remove the class `hidden`

https://github.com/godofredoninja/simply/blob/cc21e3c9f70a939bf4169f7001c05ce8271898ad/partials/layout/header.hbs#L25
