### ISSUE TITLE
Hi, I have covid 

### ISSUE THREAD

**Issue by godofredoninja** [godofredoninja/simply#84]
Unfortunately, I want to inform you that I have COVID, I feel very bad.

If I don't make any more updates to my Ghost themes, it means that I have not overcome COVID.

I really feel very sad.

I really don't want to be bedridden, I prefer to be in front of my computer doing what I like to write code.

From here I tell you, please be very careful and protect yourself, always wear your masks and disinfect your hand every time you go out.

Well I say goodbye.

**Comment by fangonaut** [comment]
I'm very sorry to hear your news, I wish you a speedy recovery, my daughter had it in March 2020, she fell like hell for about a week then started to recover, after a month or so she was back to herself. I don't mean to downplay how bad you must be feeling right now, just give a little hope that you will be ok. Drink lots of water, and rest a lot, recent evidence suggests that not resting can increase the chances of long covid. Take care best wishes from the UK.

**Comment by fullakingi** [comment]
Sorry my friend.

**Comment by godofredoninja** [comment]
Hello 😃 

Thank you, I am recovering from my health. I have already gone through the most difficult moments. The good news is that I am still breathing.

**Comment by hexclann** [comment]
This is good to hear. Take care my friend :)

**Comment by fangonaut** [comment]
Great news! So glad you are on the mend, conserve your strength, and allow your body to heal as it needs to. Stay safe, be well. 👍 💪🍺

**Comment by godofredoninja** [comment]
Thank you. I'm already 90 percent fine.

The Covid kept me in bed for two weeks. 

And a week on oxygen.

But thank my gods I'm fine now.

Now I will continue to work on my projects and update my themes for Ghost.
