### ISSUE TITLE
Feature Request: Post carousel for featured posts

### ISSUE THREAD

**Issue by ayyilmaz** [godofredoninja/simply#87]
I think it would be better to have a slider for featured posts. If you add this to one of the home page options in the future, the functionality will increase. There are also many themes. It's really nice that you are creating an open source project. Congratulations and thank you.

Some ghost themes use slider

- https://dashi.bironthemes.com/index3/
- https://alto.ghost.io/
- https://ease.ghost.io/
- https://korima.maltiv.com/
- https://liebling.eduardogomez.io/

**Comment by godofredoninja** [comment]
Hi @ayyilmaz Thanks for your suggestions

I have just added two templates with Slider

- [Featured with Slider](https://godofredo.ninja/ghost-theme/simply/home-page/#featuredwithslider)
- [Photographer](https://godofredo.ninja/ghost-theme/simply/home-page/#photographer)

😄

**Comment by ayyilmaz** [comment]
You are great but unfortunately ı have to give up Ghost CMS because of [some bugs of Ghost CLI](https://github.com/TryGhost/Ghost-CLI/issues/460#issuecomment-804236928). I moved from Centos to Ubuntu and I use HestiaCP so I could not install :( 

But I know you are great man and your amazing contribution to the open source ecosystem is admirable :100:
