### ISSUE TITLE
Theme compatibility for Ghost Version 4.x

### ISSUE THREAD

**Issue by yogeshbeniwal** [godofredoninja/simply#89]
Ghost v4.x is out. [Gscan](https://gscan.ghost.org/) is reporting few warnings and recommendations. 

- [x] Warning: The {{@labs.members}} helper should not be used.
- [x] Warning: Replace {{[#].currency_symbol}} with {{price currency=currency}}.
- [x] Warning: The {{@site.lang}} helper should be replaced with {{@site.locale}}
- [x] Warning: The default visibility for posts in {{#foreach}} block helper has changed in v4.
- [x] Warning: The default_payment_card_last4 field now coalesces to **** in Ghost 4.x instead of null.
- [x] Recommendation: The use of visibility="all" is no longer required for posts in {{#foreach}} helper.

**Comment by godofredoninja** [comment]
Hi @yogeshbeniwal 

I have just updated. When I recover from my health I will add interesting things to the theme.
