### ISSUE TITLE
How to remove `Design with  by @GodoFredoNinja` from footer

### ISSUE THREAD

**Issue by ksurendra** [godofredoninja/simply#98]
Great theme and docs.

How can we remove `Design with  by @GodoFredoNinja` from footer?

**Comment by ksurendra** [comment]
any update on this?

**Comment by Aerya** [comment]
It's not fair. But look at the code.

**Comment by ksurendra** [comment]
Hey sorry didn't meant to remove credentials.

**Comment by godofredoninja** [comment]
Don't forget about me. I'm still alive  😭
